### ISSUE TITLE
Wrong order of arguments

### ISSUE THREAD

**Issue by toyboot4e** [silenttowergames/stonetower#1]
Thank you for sharing this!

I read [this line](https://github.com/silenttowergames/stonetower/blob/338e8500d3573dc306f5c4a637a5462f16bab4bd/src/Rendering/Sprites/SpriteBatchFunctions.c#L202) and it looks like an error; the position of `elementSizeInBytes` might be wrong. But I'm really not sure about FNA3D so excuse me if it's correct. 

`SpriteBatchFunctions.c`:

```c
FNA3D_SetVertexBufferData(
    device,
    spriteBatch->vertexBuffer,
    0,
    spriteBatch->vertices,
    sizeof(Vertex) * 6 * spriteBatch->spriteDrawCountThisFrame, // this ////////////////////////////
    1, // and this ////////////////////////////
    1,
    FNA3D_SETDATAOPTIONS_DISCARD);
```

`FNA3D.h`:

```c
FNA3DAPI void FNA3D_SetVertexBufferData(
	FNA3D_Device *device,
	FNA3D_Buffer *buffer,
	int32_t offsetInBytes,
	void* data,
	int32_t elementCount, // this ////////////////////////////
	int32_t elementSizeInBytes, // and this ////////////////////////////
	int32_t vertexStride,
	FNA3D_SetDataOptions options
);
```

**Comment by toyboot4e** [comment]
Oh I should have read the comment on `FNA3D_SetVertexBufferData` in `FNA3D.h`

**Comment by silenttowergames** [comment]
Yeah, it seems to be an XNA backwards compatibility thing. I appreciate you taking the time to read the code & open an issue though!
